### ISSUE TITLE
Help configuring session data

### ISSUE THREAD

**Issue by lebogan** [aca-labs/crystal-snmp#3]
Thanks for your response to this noob question if this is the right place to ask. I want to change the `auth_protocol` and `priv_protocol` on the fly:
```
    session = SNMP::V3::Session.new(args[:user],
      args[:auth_pass],
      args[:priv_pass],
      auth_protocol: SNMP::V3::Security::AuthProtocol::MD5,
      priv_protocol: SNMP::V3::Security::PrivacyProtocol::AES)
```
I can't for the life of me figure out to change that `MD5` to `SHA` on the fly. I get the input from the user as a string. That's the stuff in `args`. And that's where I'm stuck.

This kinda works but feels clunky:
```
    security = {md5: SNMP::V3::Security::AuthProtocol::MD5,
                sha: SNMP::V3::Security::AuthProtocol::SHA}
    encryption = {des: SNMP::V3::Security::PrivacyProtocol::DES,
                  aes: SNMP::V3::Security::PrivacyProtocol::AES}
 
    session = SNMP::V3::Session.new(args[:user],
      args[:auth_pass],
      args[:priv_pass],
      auth_protocol: args[:auth] == "sha" ? security[:sha] : security[:md5],
      priv_protocol: args[:priv] == "aes" ? encryption[:aes] : encryption[:des])
```
Like I said, seriously noob. Thanks for this great shard.

**Comment by stakach** [comment]
it should actually work if you use Symbols I think
So if `args[:auth] == :sha` then you can pass the argument in directly

At the very least I think you can do: `args[:auth] == "sha" ? :sha : :md5` as crystal converts Symbols to Enums where the types are clear enough

Otherwise if what you've done works, it's not bad

**Comment by stakach** [comment]
The other thing you could do is convert the string to the correct type before calling the function

```crystal
auth = case args[:auth]
when "sha"
  SNMP::V3::Security::AuthProtocol::SHA
when "md5"
  SNMP::V3::Security::AuthProtocol::MD5
else
  raise "invalid auth protocol selected"
end
```

this would ensure it errors on invalid input instead of using MD5

**Comment by lebogan** [comment]
Sweet! Converting the string before the function call cleaned up both the function and removed the conditionals from my session object within the function. This just feels cleaner. Thank you so much for the guidance. I will close this.
