### ISSUE TITLE
Question on tag types for timeticks

### ISSUE THREAD

**Issue by lebogan** [aca-labs/crystal-snmp#5]
I am trying to represent sysUpTimeInstance as xx:xx:xx:xx.x the way snmpwalk does. The ASN.1::BER output yields `tag_class=Aplication tag_number=3 payload=Bytes[54,182,159,25]`. So far, I have tried get_unsigned32 and get_bytes helpers and then tried to convert them into the above format. Do you have any experience with this type of conversion?

If the unsigned32 value is seconds, then it looks like all I need to do is some math. Does that seem reasonable?

Please, disregard if this question is too noob. Thanks for any input.

**Comment by stakach** [comment]
Fairly certain the time ticks are 1/100th of a second.
So you can do

```crystal
# convert to 64bit as we're going to times by 10 to get the milliseconds which are easier to work with
ticks = message.get_unsigned32.to_u64
(ticks * 10).milliseconds #=> Time::Span
```

The time span should be pretty easy to manipulate for display
https://crystal-lang.org/api/0.35.1/Time/Span.html

**Comment by stakach** [comment]
Good explanation here: https://knowledge.broadcom.com/external/article/167562/why-does-the-snmp-value-for-sysuptime-ov.html

**Comment by lebogan** [comment]
Whew, that certainly cut out all the kludgy math I had figured out. And it's cleaner. 
I also tried for comparison:
```
ticks = message.value.get_unsigned64
```
Sweet! Thanks for the explanations. I am constantly blown away by how much punch crystal packs in its stdlib.
