### ISSUE TITLE
Errors using Helpers::IfEntry class

### ISSUE THREAD

**Issue by lebogan** [aca-labs/crystal-snmp#6]
I recently ran into this error using that class:
```
enum IfAdminStatus
Error: can't reopen enum and add more constants to it
```
crystal v1.1.1
snmp v0.9.7

Because I'm not a professional developer, I am prone to try stupid things. I moved the enum blocks to a place above the initialize method and everything worked. I can't find anything in the documentation explaining why this happens. Does placement really matter? Any ideas? 

Thanks.

**Comment by stakach** [comment]
cut a new release v0.9.8
I haven't run into that issue but happy to make the change :)
